version: '3'
services:
  ledger-client:
    build: ./ledger-client
    ports:
    - 8080:3000
  eventstore:
    image: eventstore/eventstore:release-4.1.1
    environment:
      EVENTSTORE_START_STANDARD_PROJECTIONS: 'true'
    ports:
    - 2113:2113
    - 1113:1113
